// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use hardcoded values as per Lovable Supabase instructions
const SUPABASE_URL = 'https://tiaojwumxgdnobknlyqp.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpYW9qd3VteGdkbm9ia25seXFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU0OTEwNzIsImV4cCI6MjA4MTA2NzA3Mn0.K-FP686ddEyUKoFS9BHQ4rWc1bbn2IQ6OAY1y4WLMx8';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});